### PR TITLE
JENKINS-42640: Fix parsing int and float parameter values

### PR DESCRIPTION
**Pull request by jviolas**
I think parsing the value from the input will fix the issue of having the value serialized as a string instead of a Integer or a decimal

### CODE REVIEW

**Comment by michaelneale** [comment]
nice one - will give this a try. will input type of number stop this from capturing invalid values from the user that would trip up parse?

**Comment by jviolas** [comment]
@michaelneale The input seems to already avoid user to enter any invalid value, so I think the value can always be parsed as int or float. The only "invalid" value I think user can set is an empty value, but I think in this case, the property editor fallback in an other case a display an error.

Just one other thing, I didn't try to edit edit a step with a "DecimalProperty" (I don't know which one has it), but the render is exactly the same as the IntegerPropertyInput, so I'm not sure user can really enter a decimal value (or is it by setting the dataTypes that React change the input behavior ?)

**Comment by michaelneale** [comment]
LGTM @kzantow may as well get it in

**Comment by kzantow** [comment]
Thanks for your contribution! :)

**Comment by jviolas** [comment]
Small contribution, but happy to help ;)
We found the issue during a meetup about pipelines animated by @batmat, so I tried to fix it afterward.

**Comment by batmat** [comment]
\o/

Related: https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/133

**Comment by michaelneale** [comment]
right yes I saw there was some hackathon thing going on - nice one!

**Pull request merged**
